/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.awt.Component;
import java.awt.Graphics;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import registros.Libro;

/**
 *
 * @author mdiazm97
 */
public class VentanaAplicacion extends javax.swing.JFrame {

    private ArrayList<Libro> books = new ArrayList();

    private static Vector<Vector<String>> languages = new Vector();

    private int selectedLanguage;

    private Boolean appRunning = false;

    /**
     * Creates new form VentanaAplicacion
     */
    public VentanaAplicacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainWindow = new javax.swing.JFrame();
        addBook = new javax.swing.JButton();
        editBook = new javax.swing.JButton();
        delBook = new javax.swing.JButton();
        getBooks = new javax.swing.JButton();
        numberBooks = new javax.swing.JLabel();
        languageSelected = new javax.swing.JLabel();
        flag = new javax.swing.JLabel();
        imgMainLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        importOption = new javax.swing.JMenuItem();
        export = new javax.swing.JMenuItem();
        preferences = new javax.swing.JMenu();
        changeLanguageOption = new javax.swing.JMenuItem();
        importWindow = new javax.swing.JFrame();
        fileChooser = new javax.swing.JFileChooser();
        addWindow = new javax.swing.JFrame();
        addBookLabel = new javax.swing.JLabel();
        isbnText = new javax.swing.JTextField();
        titleText = new javax.swing.JTextField();
        authorText = new javax.swing.JTextField();
        isAEspecialEdition = new javax.swing.JCheckBox();
        registerBook = new javax.swing.JButton();
        cancelRegister = new javax.swing.JButton();
        isbnLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        authorLabel = new javax.swing.JLabel();
        queryWindow = new javax.swing.JFrame();
        queryLabel = new javax.swing.JLabel();
        closeQuery = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        queryTable = new javax.swing.JTable();
        errorWindow = new javax.swing.JFrame();
        errorLabel = new javax.swing.JLabel();
        errorIcon = new javax.swing.JLabel();
        acceptError = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        errorTextArea = new javax.swing.JTextPane();
        deleteWindow = new javax.swing.JFrame();
        deleteBookLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        deleteList = new javax.swing.JList<>();
        deleteButton = new javax.swing.JButton();
        deleteCancelButton = new javax.swing.JButton();
        deleteConfirmWindow = new javax.swing.JFrame();
        deleteConfirmImg = new javax.swing.JLabel();
        deleteAttentionConfirmLabel = new javax.swing.JLabel();
        deleteAcceptConfirmButton = new javax.swing.JButton();
        deleteCancelConfirmButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        deleteConfirmText = new javax.swing.JTextPane();
        editWindow = new javax.swing.JFrame();
        editWindowLabel = new javax.swing.JLabel();
        editISBN = new javax.swing.JTextField();
        editTitle = new javax.swing.JTextField();
        editAuthor = new javax.swing.JTextField();
        editSpecialEdition = new javax.swing.JCheckBox();
        editISBNLabel = new javax.swing.JLabel();
        editTitleLabel = new javax.swing.JLabel();
        editAuthorLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        editList = new javax.swing.JList<>();
        acceptEdit = new javax.swing.JButton();
        cancelEdit = new javax.swing.JButton();
        changeLanguageWindow = new javax.swing.JFrame();
        changeLanguageLabel = new javax.swing.JLabel();
        languageList = new javax.swing.JComboBox<>();
        acceptLanguageChange = new javax.swing.JButton();
        cancelLanguageChange = new javax.swing.JButton();
        actualLanguage = new javax.swing.JLabel();
        exportWindow = new javax.swing.JFrame();
        exportFileLabel = new javax.swing.JLabel();
        exportName = new javax.swing.JTextField();
        exportButton = new javax.swing.JButton();
        exportCancelButton = new javax.swing.JButton();
        welcomeLabel = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        mainLanguageList = new javax.swing.JComboBox<>();
        selectLanguage = new javax.swing.JLabel();

        mainWindow.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        mainWindow.setTitle("Lib2000");
        mainWindow.setSize(new java.awt.Dimension(600, 400));
        mainWindow.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addBook.setFont(new java.awt.Font("American Typewriter", 0, 13)); // NOI18N
        addBook.setText("add");
        addBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookActionPerformed(evt);
            }
        });
        mainWindow.getContentPane().add(addBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 226, 150, 65));

        editBook.setFont(new java.awt.Font("American Typewriter", 0, 13)); // NOI18N
        editBook.setText("edit");
        editBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBookActionPerformed(evt);
            }
        });
        mainWindow.getContentPane().add(editBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 226, 150, 65));

        delBook.setFont(new java.awt.Font("American Typewriter", 0, 13)); // NOI18N
        delBook.setText("delete");
        delBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBookActionPerformed(evt);
            }
        });
        mainWindow.getContentPane().add(delBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 226, 150, 65));

        getBooks.setFont(new java.awt.Font("American Typewriter", 0, 13)); // NOI18N
        getBooks.setText("query");
        getBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getBooksActionPerformed(evt);
            }
        });
        mainWindow.getContentPane().add(getBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 120, 150, 65));

        numberBooks.setFont(new java.awt.Font("American Typewriter", 0, 18)); // NOI18N
        numberBooks.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        numberBooks.setText("numLibros");
        mainWindow.getContentPane().add(numberBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 317, 486, -1));

        languageSelected.setFont(new java.awt.Font("American Typewriter", 0, 13)); // NOI18N
        languageSelected.setText("jLabel1");
        mainWindow.getContentPane().add(languageSelected, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 180, 29));

        flag.setText("jLabel1");
        mainWindow.getContentPane().add(flag, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, -1));

        imgMainLabel.setText("jLabel1");
        mainWindow.getContentPane().add(imgMainLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        file.setText("File");

        importOption.setText("import");
        importOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importOptionActionPerformed(evt);
            }
        });
        file.add(importOption);

        export.setText("export");
        export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportActionPerformed(evt);
            }
        });
        file.add(export);

        jMenuBar1.add(file);

        preferences.setText("Edit");

        changeLanguageOption.setText("jMenuItem1");
        changeLanguageOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeLanguageOptionActionPerformed(evt);
            }
        });
        preferences.add(changeLanguageOption);

        jMenuBar1.add(preferences);

        mainWindow.setJMenuBar(jMenuBar1);

        importWindow.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        importWindow.setSize(new java.awt.Dimension(600, 400));

        fileChooser.setApproveButtonText("Abrir");
        fileChooser.setCurrentDirectory(null);
        fileChooser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fileChooser.setLocation(new java.awt.Point(0, 23));
        fileChooser.setMaximumSize(new java.awt.Dimension(600, 400));
        fileChooser.setMinimumSize(new java.awt.Dimension(600, 400));
        fileChooser.setPreferredSize(new java.awt.Dimension(600, 400));
        fileChooser.setSize(new java.awt.Dimension(600, 400));

        javax.swing.GroupLayout importWindowLayout = new javax.swing.GroupLayout(importWindow.getContentPane());
        importWindow.getContentPane().setLayout(importWindowLayout);
        importWindowLayout.setHorizontalGroup(
            importWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        importWindowLayout.setVerticalGroup(
            importWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        addWindow.setSize(new java.awt.Dimension(600, 400));

        addBookLabel.setFont(new java.awt.Font("American Typewriter", 0, 36)); // NOI18N
        addBookLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addBookLabel.setText("Add a book");

        isbnText.setFont(new java.awt.Font("American Typewriter", 0, 13)); // NOI18N
        isbnText.setText("ISBN");
        isbnText.setToolTipText("");

        titleText.setFont(new java.awt.Font("American Typewriter", 0, 13)); // NOI18N
        titleText.setText("Title");

        authorText.setFont(new java.awt.Font("American Typewriter", 0, 13)); // NOI18N
        authorText.setText("Author");

        isAEspecialEdition.setFont(new java.awt.Font("American Typewriter", 0, 13)); // NOI18N
        isAEspecialEdition.setText("This book is an especial edition");

        registerBook.setText("Register");
        registerBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBookActionPerformed(evt);
            }
        });

        cancelRegister.setText("Cancel");
        cancelRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelRegisterActionPerformed(evt);
            }
        });

        isbnLabel.setText("ISBN");

        titleLabel.setText("Title");

        authorLabel.setText("Author");

        javax.swing.GroupLayout addWindowLayout = new javax.swing.GroupLayout(addWindow.getContentPane());
        addWindow.getContentPane().setLayout(addWindowLayout);
        addWindowLayout.setHorizontalGroup(
            addWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addWindowLayout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addGroup(addWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addWindowLayout.createSequentialGroup()
                        .addComponent(addBookLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addWindowLayout.createSequentialGroup()
                        .addGroup(addWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(isbnLabel)
                            .addComponent(titleLabel)
                            .addComponent(authorLabel))
                        .addGap(18, 18, 18)
                        .addGroup(addWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(isbnText)
                            .addComponent(titleText)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addWindowLayout.createSequentialGroup()
                                .addComponent(isAEspecialEdition)
                                .addGap(68, 68, 68))
                            .addGroup(addWindowLayout.createSequentialGroup()
                                .addComponent(registerBook, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancelRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(authorText, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(153, 153, 153))))
        );
        addWindowLayout.setVerticalGroup(
            addWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addWindowLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(addBookLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(addWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isbnText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isbnLabel))
                .addGap(31, 31, 31)
                .addGroup(addWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleLabel))
                .addGap(31, 31, 31)
                .addGroup(addWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(authorText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(authorLabel))
                .addGap(18, 18, 18)
                .addComponent(isAEspecialEdition)
                .addGap(18, 18, 18)
                .addGroup(addWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerBook)
                    .addComponent(cancelRegister))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        queryWindow.setSize(new java.awt.Dimension(600, 400));

        queryLabel.setFont(new java.awt.Font("American Typewriter", 0, 36)); // NOI18N
        queryLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        queryLabel.setText("Consult your books");

        closeQuery.setFont(new java.awt.Font("American Typewriter", 0, 13)); // NOI18N
        closeQuery.setText("Close");
        closeQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeQueryActionPerformed(evt);
            }
        });

        queryTable.setFont(new java.awt.Font("American Typewriter", 0, 12)); // NOI18N
        queryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(queryTable);

        javax.swing.GroupLayout queryWindowLayout = new javax.swing.GroupLayout(queryWindow.getContentPane());
        queryWindow.getContentPane().setLayout(queryWindowLayout);
        queryWindowLayout.setHorizontalGroup(
            queryWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(queryWindowLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(queryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, queryWindowLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(queryWindowLayout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(closeQuery, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        queryWindowLayout.setVerticalGroup(
            queryWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(queryWindowLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(queryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(closeQuery)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        errorWindow.setSize(new java.awt.Dimension(400, 300));
        errorWindow.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        errorLabel.setFont(new java.awt.Font("American Typewriter", 0, 24)); // NOI18N
        errorLabel.setText("jLabel1");
        errorWindow.getContentPane().add(errorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 219, 80));

        errorIcon.setText("jLabel1");
        errorWindow.getContentPane().add(errorIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        acceptError.setText("OK");
        acceptError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptErrorActionPerformed(evt);
            }
        });
        errorWindow.getContentPane().add(acceptError, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 92, -1));

        jScrollPane2.setViewportView(errorTextArea);

        errorWindow.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 230, 80));

        deleteWindow.setSize(new java.awt.Dimension(600, 400));

        deleteBookLabel.setFont(new java.awt.Font("American Typewriter", 0, 36)); // NOI18N
        deleteBookLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deleteBookLabel.setText("Delete a book");

        deleteList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(deleteList);

        deleteButton.setText("jButton1");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        deleteCancelButton.setText("jButton2");
        deleteCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deleteWindowLayout = new javax.swing.GroupLayout(deleteWindow.getContentPane());
        deleteWindow.getContentPane().setLayout(deleteWindowLayout);
        deleteWindowLayout.setHorizontalGroup(
            deleteWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteWindowLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(deleteWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deleteWindowLayout.createSequentialGroup()
                        .addComponent(deleteBookLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(77, Short.MAX_VALUE))
                    .addGroup(deleteWindowLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(deleteWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(deleteCancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(104, 104, 104))))
        );
        deleteWindowLayout.setVerticalGroup(
            deleteWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteWindowLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(deleteBookLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(deleteWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deleteWindowLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(deleteWindowLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(deleteButton)
                        .addGap(35, 35, 35)
                        .addComponent(deleteCancelButton)))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        deleteConfirmWindow.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        deleteConfirmWindow.setSize(new java.awt.Dimension(400, 300));

        deleteConfirmImg.setText("jLabel1");

        deleteAttentionConfirmLabel.setFont(new java.awt.Font("American Typewriter", 0, 24)); // NOI18N
        deleteAttentionConfirmLabel.setText("jLabel1");

        deleteAcceptConfirmButton.setText("accept");
        deleteAcceptConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAcceptConfirmButtonActionPerformed(evt);
            }
        });

        deleteCancelConfirmButton.setText("cancel");
        deleteCancelConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCancelConfirmButtonActionPerformed(evt);
            }
        });

        jScrollPane5.setViewportView(deleteConfirmText);

        javax.swing.GroupLayout deleteConfirmWindowLayout = new javax.swing.GroupLayout(deleteConfirmWindow.getContentPane());
        deleteConfirmWindow.getContentPane().setLayout(deleteConfirmWindowLayout);
        deleteConfirmWindowLayout.setHorizontalGroup(
            deleteConfirmWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteConfirmWindowLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteAcceptConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteCancelConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(deleteConfirmWindowLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(deleteConfirmImg)
                .addGap(38, 38, 38)
                .addGroup(deleteConfirmWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteAttentionConfirmLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        deleteConfirmWindowLayout.setVerticalGroup(
            deleteConfirmWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteConfirmWindowLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(deleteConfirmWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteConfirmImg, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteAttentionConfirmLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(deleteConfirmWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteCancelConfirmButton)
                    .addComponent(deleteAcceptConfirmButton))
                .addGap(25, 25, 25))
        );

        editWindow.setSize(new java.awt.Dimension(600, 400));

        editWindowLabel.setFont(new java.awt.Font("American Typewriter", 0, 36)); // NOI18N
        editWindowLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editWindowLabel.setText("Editing a book");

        editSpecialEdition.setText("jCheckBox1");

        editISBNLabel.setText("jLabel1");

        editTitleLabel.setText("jLabel2");

        editAuthorLabel.setText("jLabel3");

        editList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        editList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        editList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(editList);

        acceptEdit.setText("jButton1");
        acceptEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptEditActionPerformed(evt);
            }
        });

        cancelEdit.setText("jButton1");
        cancelEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editWindowLayout = new javax.swing.GroupLayout(editWindow.getContentPane());
        editWindow.getContentPane().setLayout(editWindowLayout);
        editWindowLayout.setHorizontalGroup(
            editWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editWindowLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(editWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(editISBNLabel)
                    .addComponent(editTitleLabel)
                    .addComponent(editAuthorLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(editWindowLayout.createSequentialGroup()
                        .addGroup(editWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(editISBN)
                            .addComponent(editTitle)
                            .addComponent(editAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))
                    .addGroup(editWindowLayout.createSequentialGroup()
                        .addComponent(editSpecialEdition)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(acceptEdit)
                        .addGap(18, 18, 18)
                        .addComponent(cancelEdit)
                        .addGap(50, 50, 50))))
            .addGroup(editWindowLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(editWindowLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        editWindowLayout.setVerticalGroup(
            editWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editWindowLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(editWindowLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(editWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editWindowLayout.createSequentialGroup()
                        .addGroup(editWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editISBNLabel))
                        .addGap(42, 42, 42)
                        .addGroup(editWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editTitleLabel))
                        .addGap(41, 41, 41)
                        .addGroup(editWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editAuthorLabel)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(editWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editWindowLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(editSpecialEdition))
                    .addGroup(editWindowLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(editWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(acceptEdit)
                            .addComponent(cancelEdit))))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        changeLanguageWindow.setLocation(new java.awt.Point(40, 40));
        changeLanguageWindow.setSize(new java.awt.Dimension(400, 300));

        changeLanguageLabel.setFont(new java.awt.Font("American Typewriter", 0, 24)); // NOI18N
        changeLanguageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        changeLanguageLabel.setText("Seleccione un idioma:");

        languageList.setFont(new java.awt.Font("American Typewriter", 0, 13)); // NOI18N

        acceptLanguageChange.setFont(new java.awt.Font("American Typewriter", 0, 13)); // NOI18N
        acceptLanguageChange.setText("jButton1");
        acceptLanguageChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptLanguageChangeActionPerformed(evt);
            }
        });

        cancelLanguageChange.setFont(new java.awt.Font("American Typewriter", 0, 13)); // NOI18N
        cancelLanguageChange.setText("jButton2");
        cancelLanguageChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelLanguageChangeActionPerformed(evt);
            }
        });

        actualLanguage.setFont(new java.awt.Font("American Typewriter", 0, 13)); // NOI18N
        actualLanguage.setText("jLabel1");

        javax.swing.GroupLayout changeLanguageWindowLayout = new javax.swing.GroupLayout(changeLanguageWindow.getContentPane());
        changeLanguageWindow.getContentPane().setLayout(changeLanguageWindowLayout);
        changeLanguageWindowLayout.setHorizontalGroup(
            changeLanguageWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changeLanguageWindowLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(actualLanguage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(acceptLanguageChange)
                .addGap(18, 18, 18)
                .addComponent(cancelLanguageChange)
                .addGap(32, 32, 32))
            .addGroup(changeLanguageWindowLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(changeLanguageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, changeLanguageWindowLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(languageList, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );
        changeLanguageWindowLayout.setVerticalGroup(
            changeLanguageWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changeLanguageWindowLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(changeLanguageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(languageList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(changeLanguageWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acceptLanguageChange)
                    .addComponent(cancelLanguageChange)
                    .addComponent(actualLanguage))
                .addGap(34, 34, 34))
        );

        exportWindow.setLocation(new java.awt.Point(300, 300));
        exportWindow.setSize(new java.awt.Dimension(300, 200));

        exportFileLabel.setFont(new java.awt.Font("American Typewriter", 0, 13)); // NOI18N
        exportFileLabel.setText("jLabel1");

        exportName.setText("jTextField1");

        exportButton.setText("jButton1");
        exportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportButtonActionPerformed(evt);
            }
        });

        exportCancelButton.setText("jButton1");
        exportCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout exportWindowLayout = new javax.swing.GroupLayout(exportWindow.getContentPane());
        exportWindow.getContentPane().setLayout(exportWindowLayout);
        exportWindowLayout.setHorizontalGroup(
            exportWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exportWindowLayout.createSequentialGroup()
                .addGroup(exportWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(exportWindowLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(exportWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exportName, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(exportWindowLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(exportButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(exportCancelButton))))
                    .addGroup(exportWindowLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(exportFileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        exportWindowLayout.setVerticalGroup(
            exportWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exportWindowLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(exportFileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(exportName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(exportWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exportButton)
                    .addComponent(exportCancelButton))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lib2000");

        welcomeLabel.setFont(new java.awt.Font("American Typewriter", 0, 24)); // NOI18N
        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel.setText("Hola");
        welcomeLabel.setToolTipText("");
        welcomeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        startButton.setFont(new java.awt.Font("American Typewriter", 0, 13)); // NOI18N
        startButton.setText("jButton1");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        title.setFont(new java.awt.Font("American Typewriter", 0, 48)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Lib2000");
        title.setToolTipText("");

        mainLanguageList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainLanguageListActionPerformed(evt);
            }
        });

        selectLanguage.setFont(new java.awt.Font("American Typewriter", 0, 13)); // NOI18N
        selectLanguage.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(106, Short.MAX_VALUE)
                        .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(selectLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mainLanguageList, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(welcomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainLanguageList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectLanguage))
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:

        numberBooks.setText(indicatorText + books.size());
        mainWindow.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_startButtonActionPerformed

    private void importOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importOptionActionPerformed

        File f = null;

        File currentDir = new File(System.getProperty("user.dir"));

        fileChooser.setCurrentDirectory(currentDir);
        fileChooser.setDialogTitle(titleLoadFile);
        fileChooser.setApproveButtonText(openLabel);
        //fileChooser.set

        int status = fileChooser.showOpenDialog(null);

        if (status == JFileChooser.APPROVE_OPTION) {
            f = fileChooser.getSelectedFile();

            readRegisterFile(f);

            System.out.println(f.getName());
        } else {
            System.out.println("No se ha seleccionado ningún fichero");
        }

    }//GEN-LAST:event_importOptionActionPerformed

    private void addBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookActionPerformed
        // TODO add your handling code here:

        //mainWindow.setVisible(false);
        addWindow.setVisible(true);

    }//GEN-LAST:event_addBookActionPerformed

    private void exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportActionPerformed
        exportWindow.setVisible(true);
    }//GEN-LAST:event_exportActionPerformed

    private void registerBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBookActionPerformed
        // TODO add your handling code here:

        if (!registerHandler()) {
            errorWindow.setVisible(true);

        } else {
            addWindow.setVisible(false);
        }

        numberBooks.setText(indicatorText + books.size());

    }//GEN-LAST:event_registerBookActionPerformed

    private void cancelRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelRegisterActionPerformed
        addWindow.setVisible(false);
    }//GEN-LAST:event_cancelRegisterActionPerformed

    private void getBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getBooksActionPerformed
        tableHandler();
        queryWindow.setVisible(true);
    }//GEN-LAST:event_getBooksActionPerformed

    private void closeQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeQueryActionPerformed
        queryWindow.setVisible(false);
    }//GEN-LAST:event_closeQueryActionPerformed

    private void acceptErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptErrorActionPerformed
        // TODO add your handling code here:
        errorWindow.setVisible(false);
    }//GEN-LAST:event_acceptErrorActionPerformed

    private void deleteCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCancelButtonActionPerformed
        // TODO add your handling code here:
        deleteWindow.setVisible(false);
    }//GEN-LAST:event_deleteCancelButtonActionPerformed

    private void delBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBookActionPerformed

        titleListHandler();

        deleteWindow.setVisible(true);
    }//GEN-LAST:event_delBookActionPerformed

    private void deleteCancelConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCancelConfirmButtonActionPerformed
        // TODO add your handling code here:

        deleteConfirmWindow.setVisible(false);
    }//GEN-LAST:event_deleteCancelConfirmButtonActionPerformed

    private void deleteAcceptConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAcceptConfirmButtonActionPerformed
        int selected = deleteList.getSelectedIndex();

        books.remove(selected);

        numberBooks.setText(indicatorText + books.size());
        
        titleListHandler();
        
        deleteConfirmWindow.setVisible(false);
        deleteWindow.setVisible(false);
    }//GEN-LAST:event_deleteAcceptConfirmButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:

        if (deleteList.getSelectedIndex() >= 0) {
            deleteConfirmWindow.setVisible(true);
        } else {
            errorWindow.setVisible(true);
        }

    }//GEN-LAST:event_deleteButtonActionPerformed

    private void editListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editListMouseClicked
        // TODO add your handling code here:

        int selected = editList.getSelectedIndex();

        if (selected >= 0) {
            editISBN.setText(books.get(selected).getISBN());
            editTitle.setText(books.get(selected).getTitulo());
            editAuthor.setText(books.get(selected).getAutor());
            editSpecialEdition.setSelected(books.get(selected).getEdicionEspecial());
        }

    }//GEN-LAST:event_editListMouseClicked

    private void editBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBookActionPerformed
        // TODO add your handling code here:

        titleListHandler();

        editWindow.setVisible(true);
    }//GEN-LAST:event_editBookActionPerformed

    private void acceptEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptEditActionPerformed
        // TODO add your handling code here:

        int selectedOption = editList.getSelectedIndex();

        if (selectedOption >= 0) {
            Boolean change = true;
            for (int i = 0; i < books.size(); i++) {
                if (i != selectedOption && books.get(i).getISBN().equals(editISBN.getText())) {
                    errorWindow.setVisible(true);

                    change = false;

                    editISBN.setText(books.get(selectedOption).getISBN());

                    break;
                }
            }
            if (change == true) {
                books.get(selectedOption).setISBN(editISBN.getText());
                books.get(selectedOption).setTitle(editTitle.getText());
                books.get(selectedOption).setAuthor(editAuthor.getText());
                books.get(selectedOption).setSpecialEdition(editSpecialEdition.isSelected());

                editWindow.setVisible(false);
            }
        }


    }//GEN-LAST:event_acceptEditActionPerformed

    private void cancelEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelEditActionPerformed
        // TODO add your handling code here:

        editWindow.setVisible(false);

    }//GEN-LAST:event_cancelEditActionPerformed

    private void changeLanguageOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeLanguageOptionActionPerformed
        // TODO add your handling code here:

        // I will open a window to set the new languaje
        changeLanguageWindow.setVisible(true);

    }//GEN-LAST:event_changeLanguageOptionActionPerformed

    private void cancelLanguageChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelLanguageChangeActionPerformed
        changeLanguageWindow.setVisible(false);
    }//GEN-LAST:event_cancelLanguageChangeActionPerformed

    private void acceptLanguageChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptLanguageChangeActionPerformed
        int selectedLanguage = languageList.getSelectedIndex();

        if (selectedLanguage >= 0) {
            internazionalize(selectedLanguage);
            changeLanguageWindow.setVisible(false);
        }

    }//GEN-LAST:event_acceptLanguageChangeActionPerformed

    private void exportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportButtonActionPerformed

        String file = exportName.getText();

        if (!file.equals("")) {
            try {
                PrintWriter pw = new PrintWriter(file, "UTF-8");

                for (int i = 0; i < books.size(); i++) {
                    pw.println(books.get(i).toCSV());
                }

                pw.close();
                exportWindow.setVisible(false);

            } catch (FileNotFoundException ex) {
                Logger.getLogger(VentanaAplicacion.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(VentanaAplicacion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_exportButtonActionPerformed

    private void exportCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportCancelButtonActionPerformed
        exportWindow.setVisible(false);
    }//GEN-LAST:event_exportCancelButtonActionPerformed

    private void mainLanguageListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainLanguageListActionPerformed
        // TODO add your handling code here:

        if (appRunning) {

            int selected = mainLanguageList.getSelectedIndex();

            if (selected >= 0) {
                internazionalize(selected);
            }
        }
    }//GEN-LAST:event_mainLanguageListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAplicacion().startApplication();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptEdit;
    private javax.swing.JButton acceptError;
    private javax.swing.JButton acceptLanguageChange;
    private javax.swing.JLabel actualLanguage;
    private javax.swing.JButton addBook;
    private javax.swing.JLabel addBookLabel;
    private javax.swing.JFrame addWindow;
    private javax.swing.JLabel authorLabel;
    private javax.swing.JTextField authorText;
    private javax.swing.JButton cancelEdit;
    private javax.swing.JButton cancelLanguageChange;
    private javax.swing.JButton cancelRegister;
    private javax.swing.JLabel changeLanguageLabel;
    private javax.swing.JMenuItem changeLanguageOption;
    private javax.swing.JFrame changeLanguageWindow;
    private javax.swing.JButton closeQuery;
    private javax.swing.JButton delBook;
    private javax.swing.JButton deleteAcceptConfirmButton;
    private javax.swing.JLabel deleteAttentionConfirmLabel;
    private javax.swing.JLabel deleteBookLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton deleteCancelButton;
    private javax.swing.JButton deleteCancelConfirmButton;
    private javax.swing.JLabel deleteConfirmImg;
    private javax.swing.JTextPane deleteConfirmText;
    private javax.swing.JFrame deleteConfirmWindow;
    private javax.swing.JList<String> deleteList;
    private javax.swing.JFrame deleteWindow;
    private javax.swing.JTextField editAuthor;
    private javax.swing.JLabel editAuthorLabel;
    private javax.swing.JButton editBook;
    private javax.swing.JTextField editISBN;
    private javax.swing.JLabel editISBNLabel;
    private javax.swing.JList<String> editList;
    private javax.swing.JCheckBox editSpecialEdition;
    private javax.swing.JTextField editTitle;
    private javax.swing.JLabel editTitleLabel;
    private javax.swing.JFrame editWindow;
    private javax.swing.JLabel editWindowLabel;
    private javax.swing.JLabel errorIcon;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JTextPane errorTextArea;
    private javax.swing.JFrame errorWindow;
    private javax.swing.JMenuItem export;
    private javax.swing.JButton exportButton;
    private javax.swing.JButton exportCancelButton;
    private javax.swing.JLabel exportFileLabel;
    private javax.swing.JTextField exportName;
    private javax.swing.JFrame exportWindow;
    private javax.swing.JMenu file;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel flag;
    private javax.swing.JButton getBooks;
    private javax.swing.JLabel imgMainLabel;
    private javax.swing.JMenuItem importOption;
    private javax.swing.JFrame importWindow;
    private javax.swing.JCheckBox isAEspecialEdition;
    private javax.swing.JLabel isbnLabel;
    private javax.swing.JTextField isbnText;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JComboBox<String> languageList;
    private javax.swing.JLabel languageSelected;
    private javax.swing.JComboBox<String> mainLanguageList;
    private javax.swing.JFrame mainWindow;
    private javax.swing.JLabel numberBooks;
    private javax.swing.JMenu preferences;
    private javax.swing.JLabel queryLabel;
    private javax.swing.JTable queryTable;
    private javax.swing.JFrame queryWindow;
    private javax.swing.JButton registerBook;
    private javax.swing.JLabel selectLanguage;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel title;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField titleText;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables

    private String isbnHeader;
    private String titleHeader;
    private String authorHeader;
    private String specialEditionHeader;
    private String indicatorText;
    private String openLabel;
    private String titleLoadFile;

    private Boolean registerHandler() {

        String textISBN = isbnText.getText();
        String textTitle = titleText.getText();
        String textAuthor = authorText.getText();

        if (textISBN.equals("") || textTitle.equals("") || textAuthor.equals("")) {
            // Mostrar ventana de error de que falta un dato
            return false;
        }

        for (int i = 0; i < books.size(); i++) {
            if (books.get(i).getISBN().equals(textISBN)) {
                return false;
            }
        }

        Libro b = new Libro(textISBN, textTitle, textAuthor, isAEspecialEdition.isSelected());

        books.add(b);

        return true;
    }

    private void tableHandler() {

        DefaultTableModel model = new DefaultTableModel(new String[]{isbnHeader, titleHeader, authorHeader, specialEditionHeader}, 0);
        queryTable.setModel(model);
        for (int i = 0; i < books.size(); i++) {
            model.addRow(new Object[]{books.get(i).getISBN(), books.get(i).getTitulo(), books.get(i).getAutor(), "No"});
        }
    }

    private void titleListHandler() {

        DefaultListModel<String> model = new DefaultListModel();

        for (int i = 0; i < books.size(); i++) {
            model.addElement(books.get(i).getTitulo());
        }

        deleteList.setModel(model);
        editList.setModel(model);
    }

    private void readRegisterFile(File f) {
        try (BufferedReader br = new BufferedReader(new FileReader(f.getName()))) {
            String currentLine;
            while ((currentLine = br.readLine()) != null) {
                String separador = ";";
                String isbn = "", title = "", author = "";
                Boolean special = false;

                String[] aux = currentLine.split(separador);

                isbn = aux[0];
                title = aux[1];
                author = aux[2];

                special = Boolean.valueOf(aux[3]);

                Libro l = new Libro(isbn, title, author, special);
                books.add(l);
                numberBooks.setText(indicatorText + books.size());

            }
        } catch (IOException ex) {
            Logger.getLogger(VentanaAplicacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void startApplication() { // Here, i will configure first language by default. In other function, it will be posible to set another one.

        loadLanguagesFile();

        isbnText.setText("");
        titleText.setText("");
        authorText.setText("");
        exportName.setText("");

        internazionalize(0);

        appRunning = true;
        
        this.setVisible(true);
        //mainWindow.setVisible(true);
    }

    private void internazionalize(int lang) {

        selectedLanguage = lang;

        acceptEdit.setText(languages.get(lang).get(0));
        acceptError.setText(languages.get(lang).get(0));
        acceptLanguageChange.setText(languages.get(lang).get(0));
        actualLanguage.setText(languages.get(lang).get(1));
        addBook.setText(languages.get(lang).get(2));
        addBookLabel.setText(languages.get(lang).get(3));
        addWindow.setTitle(languages.get(lang).get(4));
        authorLabel.setText(languages.get(lang).get(5));
        cancelEdit.setText(languages.get(lang).get(6));
        cancelLanguageChange.setText(languages.get(lang).get(6));
        cancelRegister.setText(languages.get(lang).get(6));
        changeLanguageLabel.setText(languages.get(lang).get(7));
        changeLanguageOption.setText(languages.get(lang).get(7));
        changeLanguageWindow.setTitle(languages.get(lang).get(8));
        closeQuery.setText(languages.get(lang).get(9));
        delBook.setText(languages.get(lang).get(10));
        deleteAcceptConfirmButton.setText(languages.get(lang).get(0));
        deleteAttentionConfirmLabel.setText(languages.get(lang).get(11));
        deleteBookLabel.setText(languages.get(lang).get(12));
        deleteButton.setText(languages.get(lang).get(13));
        deleteCancelButton.setText(languages.get(lang).get(6));
        deleteCancelConfirmButton.setText(languages.get(lang).get(6));
        deleteConfirmWindow.setTitle(languages.get(lang).get(15));
        deleteConfirmText.setText(languages.get(lang).get(14));
        deleteWindow.setTitle(languages.get(lang).get(15));
        preferences.setText(languages.get(lang).get(31));
        editAuthorLabel.setText(languages.get(lang).get(5));
        editBook.setText(languages.get(lang).get(17));
        editISBNLabel.setText(languages.get(lang).get(18));
        editSpecialEdition.setText(languages.get(lang).get(19));
        editTitleLabel.setText(languages.get(lang).get(20));
        editWindow.setTitle(languages.get(lang).get(21));
        editWindowLabel.setText(languages.get(lang).get(22));
        errorLabel.setText(languages.get(lang).get(23));
        errorTextArea.setText(languages.get(lang).get(24));
        errorWindow.setTitle(languages.get(lang).get(25));
        export.setText(languages.get(lang).get(26));
        exportButton.setText(languages.get(lang).get(26));
        exportCancelButton.setText(languages.get(lang).get(6));
        exportFileLabel.setText(languages.get(lang).get(27));
        exportWindow.setTitle(languages.get(lang).get(28));
        file.setText(languages.get(lang).get(29));
        getBooks.setText(languages.get(lang).get(30));
        importOption.setText(languages.get(lang).get(32));
        importWindow.setTitle(languages.get(lang).get(33));
        isAEspecialEdition.setText(languages.get(lang).get(19));
        isbnLabel.setText(languages.get(lang).get(18));
        languageSelected.setText(languages.get(lang).get(34));
        mainWindow.setTitle(languages.get(lang).get(35));
        selectLanguage.setText(languages.get(lang).get(7));

        isbnHeader = languages.get(lang).get(18);
        titleHeader = languages.get(lang).get(20);
        authorHeader = languages.get(lang).get(5);
        specialEditionHeader = languages.get(lang).get(41);
        indicatorText = languages.get(lang).get(43);

        queryLabel.setText(languages.get(lang).get(36));
        queryWindow.setTitle(languages.get(lang).get(36));
        registerBook.setText(languages.get(lang).get(37));
        startButton.setText(languages.get(lang).get(38));
        title.setText(languages.get(lang).get(39));
        titleLabel.setText(languages.get(lang).get(20));
        welcomeLabel.setText(languages.get(lang).get(40));
        titleLoadFile = languages.get(lang).get(33);
        openLabel = languages.get(lang).get(42);

        imgMainLabel.setText("");
        imgMainLabel.setIcon(new javax.swing.ImageIcon(languages.get(lang).get(44)));
       
        errorIcon.setText("");
        errorIcon.setIcon(new javax.swing.ImageIcon(languages.get(lang).get(46)));

        deleteConfirmImg.setText("");
        deleteConfirmImg.setIcon(new javax.swing.ImageIcon(languages.get(lang).get(47)));
        
        flag.setText("");
        flag.setIcon(new javax.swing.ImageIcon(languages.get(lang).get(45)));

    }

    private void loadLanguagesFile() {
        //File f = new File(System.getProperty("user.dir"));

        File f = new File("lang.txt");
        Vector<String> imgVector = new Vector();

        Vector<String> aux = new Vector();
        int numLineas = 1;
        System.out.println(f.getAbsolutePath());

        try (BufferedReader br = new BufferedReader(new FileReader(f.getName()))) {
            String currentLine;

            numLineas = Integer.parseInt(br.readLine()); // Nos devuelve el número de líneas de un idioma

            while ((currentLine = br.readLine()) != null) {
                if (currentLine.lastIndexOf("img") == -1) {
                    aux.add(currentLine);
                }

            }
        } catch (IOException ex) {
            Logger.getLogger(VentanaAplicacion.class.getName()).log(Level.SEVERE, null, ex);
        }

        int numIdiomas = (int) Math.ceil((aux.size() - 1) / numLineas);

        System.out.println(numIdiomas);

        for (int i = 0; i < numIdiomas; i++) {
            languages.add(new Vector<String>());
        }

        try (BufferedReader br = new BufferedReader(new FileReader(f.getName()))) {
            String currentLine = br.readLine();

            numLineas = Integer.parseInt(currentLine); // Nos devuelve el número de líneas de un idioma

            int idiomasLeidos = 0;

            int cont;

            while (idiomasLeidos < numIdiomas) {

                cont = 0;
                currentLine = br.readLine();

                languageList.addItem(currentLine);
                mainLanguageList.addItem(currentLine);

                while (cont < numLineas) {
                    currentLine = br.readLine();
                    languages.get(idiomasLeidos).add(currentLine);

                    cont++;
                }

                idiomasLeidos++;
            }
            // Load the image files.

            while ((currentLine = br.readLine()) != null) {
                imgVector.add(currentLine);
            }

            int numImgLanguage = (imgVector.size() - numIdiomas) / numIdiomas;

            for (int i = 0; i < numIdiomas; i++) {
                for (int j = i * (numImgLanguage+1) + 1; j < i * (numImgLanguage+1) + numImgLanguage + 1; j++) {
                    languages.get(i).add(imgVector.get(j));
                }
            }

        } catch (IOException ex) {
            Logger.getLogger(VentanaAplicacion.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Process the image vector
    }
}
